import { useEffect } from 'react';
import type { CanvasNode, DirEntry, FileNodeData } from '../types';

const CONTEXT_START = '<!-- canvas-context-start -->';
const CONTEXT_END = '<!-- canvas-context-end -->';
const DEBOUNCE_MS = 1500;

const renderTree = (entries: DirEntry[], indent = ''): string => {
  const lines: string[] = [];
  for (let i = 0; i < entries.length; i++) {
    const entry = entries[i];
    const isLast = i === entries.length - 1;
    const prefix = indent + (isLast ? '└── ' : '├── ');
    const childIndent = indent + (isLast ? '    ' : '│   ');
    lines.push(prefix + entry.name + (entry.type === 'dir' ? '/' : ''));
    if (entry.children && entry.children.length > 0) {
      lines.push(renderTree(entry.children, childIndent));
    }
  }
  return lines.join('\n');
};

const buildBlock = (rootFolder: string, tree: DirEntry[], nodes: CanvasNode[]): string => {
  const folderName = rootFolder.split('/').pop() ?? rootFolder;
  let md = `## Canvas Workspace\n\n`;
  md += `> Auto-generated by Pulse Canvas · ${rootFolder}\n\n`;

  md += `### Project Structure\n\n`;
  md += '```\n';
  md += folderName + '/\n';
  md += renderTree(tree) + '\n';
  md += '```\n\n';

  const fileNodes = nodes.filter((n) => n.type === 'file');
  const noteNodes = fileNodes.filter((n) => !(n.data as FileNodeData).filePath);
  const linkedFiles = fileNodes.filter((n) => (n.data as FileNodeData).filePath);

  if (linkedFiles.length > 0) {
    md += `### Linked Files\n\n`;
    for (const n of linkedFiles) {
      const d = n.data as FileNodeData;
      md += `- **${n.title}** — \`${d.filePath}\`\n`;
    }
    md += '\n';
  }

  if (noteNodes.length > 0) {
    md += `### Canvas Notes\n\n`;
    for (const n of noteNodes) {
      md += `- **${n.title}**\n`;
    }
    md += '\n';
  }

  return md.trimEnd();
};

const injectSection = (existing: string, block: string): string => {
  const newSection = `${CONTEXT_START}\n${block}\n${CONTEXT_END}`;
  if (existing.includes(CONTEXT_START)) {
    const before = existing.slice(0, existing.indexOf(CONTEXT_START));
    const afterIdx = existing.indexOf(CONTEXT_END);
    const after = afterIdx >= 0 ? existing.slice(afterIdx + CONTEXT_END.length) : '';
    return `${before}${newSection}${after}`;
  }
  return existing ? `${existing.trimEnd()}\n\n${newSection}\n` : `${newSection}\n`;
};

export const useCanvasContext = (rootFolder: string | undefined, nodes: CanvasNode[]) => {
  useEffect(() => {
    if (!rootFolder) return;
    const api = window.canvasWorkspace;
    if (!api) return;

    const timer = setTimeout(async () => {
      try {
        const treeResult = await api.file.listDir(rootFolder, 3);
        if (!treeResult.ok || !treeResult.entries) return;

        const block = buildBlock(rootFolder, treeResult.entries, nodes);

        for (const fileName of ['CLAUDE.md', 'AGENTS.md']) {
          const filePath = `${rootFolder}/${fileName}`;
          const readResult = await api.file.read(filePath);
          const existing = readResult.ok && readResult.content ? readResult.content : '';
          const updated = injectSection(existing, block);
          await api.file.write(filePath, updated);
        }
      } catch {
        // silently ignore — non-critical background write
      }
    }, DEBOUNCE_MS);

    return () => clearTimeout(timer);
  }, [rootFolder, nodes]);
};
